### ISSUE TITLE
Update to 1.19.3 Please

### ISSUE THREAD

**Issue by sternschnaube** [tasgon/observable#40]
java.lang.NoSuchMethodError: 'void net.minecraft.class_4185.<init>(int, int, int, int, net.minecraft.class_2561, net.minecraft.class_4185$class_4241)'
	at observable.client.ProfileScreen.method_25426(ProfileScreen.java:123)
	at observable.client.ProfileScreen.<init>(ProfileScreen.java:41)
	at observable.Observable$PROFILE_SCREEN$2.invoke(Observable.java:61)
	at observable.Observable$PROFILE_SCREEN$2.invoke(Observable.java:61)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at observable.Observable.getPROFILE_SCREEN(Observable.java:61)
	at observable.Observable.clientInit$lambda-19(Observable.java:306)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:732)
	at dev.architectury.event.EventFactory.invokeMethod(EventFactory.java:53)
	at dev.architectury.event.EventFactory$1.handleInvocation(EventFactory.java:62)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:87)
	at jdk.proxy2/jdk.proxy2.$Proxy111.quit(Unknown Source)
	at net.minecraft.class_310.handler$zcn000$handleLogin(class_310.java:3521)
	at net.minecraft.class_310.method_18096(class_310.java:2163)
	at net.minecraft.class_310.method_18099(class_310.java:2141)
	at net.minecraft.class_412.method_36877(class_412.java:49)
	at net.minecraft.class_500.method_2548(class_500.java:244)
	at net.minecraft.class_500.method_2536(class_500.java:236)
	at net.minecraft.class_4267$class_4270.method_25402(class_4267.java:465)
	at net.minecraft.class_350.method_25402(class_350.java:372)
	at net.minecraft.class_4069.method_25402(class_4069.java:31)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:492)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:215)
	at net.minecraft.class_310.method_1523(class_310.java:1225)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by tasgon** [comment]
Release posted.

**Comment by sternschnaube** [comment]
Awesome, thank you 😍
