### ISSUE TITLE
Not running on 1.19.2

### ISSUE THREAD

**Issue by LunarDev-git** [tasgon/observable#45]
Everytime I run the command on Forge 43.2.5

I get this in the console

Exception in thread "Profiler" java.lang.NoClassDefFoundError: net/minecraft/core/registries/BuiltInRegistries
        at TRANSFORMER/observable@4.3.1/observable.server.ProfilingData$Companion.create(ProfilingData.java:44)
        at TRANSFORMER/observable@4.3.1/observable.server.Profiler.stopRunning(Profiler.java:158)
        at TRANSFORMER/observable@4.3.1/observable.server.Profiler$runWithDuration$$inlined$schedule$1.run(Profiler.java:149)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
Caused by: java.lang.ClassNotFoundException: net.minecraft.core.registries.BuiltInRegistries
        ... 5 more

**Comment by tasgon** [comment]
Observable version 4.3.1 is for Minecraft 1.19.3. Use 3.3.1 for 1.19.2.
