### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0 on startup

### ISSUE THREAD

**Issue by smemasmem** [tasgon/observable#50]
Minecraft 1.18.2
Modpack Mechanical Mastery v 1.3.0 with no additional mods or configuration changes
Prism Launcher

```
	Mod File: /C:/Users/tommy/AppData/Roaming/PrismLauncher/instances/Mechanical Mastery(1)/minecraft/mods/observable-2.2.3-forge.jar
	Failure message: Observable (observable) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 2.2.3
	Mod Issue URL: https://github.com/tasgon/observable/issues
	Exception message: java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 0
```

Stacktrace:

```Stacktrace:
	at org.objectweb.asm.ClassReader.readShort(ClassReader.java:3608) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:197) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-9.2.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchyFromFile(TransformerClassWriter.java:150) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:112) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:177) ~[modlauncher-9.1.3.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:372) ~[asm-tree-9.2.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:99) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformerClassWriter.getCommonSuperClass(TransformerClassWriter.java:59) ~[modlauncher-9.1.3.jar:?] {}
	at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1299) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.Frame.merge(Frame.java:1197) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-9.2.jar:?] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[asm-tree-9.2.jar:?] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[asm-tree-9.2.jar:?] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[asm-tree-9.2.jar:?] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:133) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?] {}
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
	at observable.server.Remapper.<clinit>(Remapper.java:25) ~[observable-2.2.3-forge.jar%23134!/:?] {re:classloading}
	at observable.forge.ObservableForge.<init>(ObservableForge.java:25) ~[observable-2.2.3-forge.jar%23134!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.2.1.jar%23192!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.2.1.jar%23191!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}```

**Comment by tasgon** [comment]
Can you share the full mod list? You might be missing [Kotlin for Forge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge).

**Comment by tasgon** [comment]
Closing due to no response.
